[decree.supreme]
trailing_whitespace = "deny"
tabs_vs_spaces = "spaces"
tab_width = 2
final_newline = "require"
line_endings = "lf"
blank_line_whitespace = "deny"

[decree.supreme.ignore.tab-character]
filenames = ["Makefile", "GNUmakefile", "makefile"]
extensions = ["md", "mdx"]

[decree.rust]
tab_width = 4
max_lines = 5000
ignore_comments = true
ignore_blank_lines = true

[decree.rust.linter]
command = "cargo-clippy"
